// <auto-generated />
using DrugBot.DataBase.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrugBot.DataBase.Migrations.Wisdom
{
    [DbContext(typeof(WisdomDbContext))]
    [Migration("20240721074647_AddDataForTests")]
    partial class AddDataForTests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("DrugBot.DataBase.Data.WisdomData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Wisdom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Wisdoms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Wisdom = "Что разум человека может постигнуть и во что он может поверить, того он способен достичь"
                        },
                        new
                        {
                            Id = 2,
                            Wisdom = "Стремитесь не к успеху, а к ценностям, которые он дает​"
                        },
                        new
                        {
                            Id = 3,
                            Wisdom = "Своим успехом я обязана тому, что никогда не оправдывалась и не принимала оправданий от других."
                        },
                        new
                        {
                            Id = 4,
                            Wisdom = "За свою карьеру я пропустил более 9000 бросков, проиграл почти 300 игр. 26 раз мне доверяли сделать финальный победный бросок, и я промахивался. Я терпел поражения снова, и снова, и снова. И именно поэтому я добился успеха."
                        },
                        new
                        {
                            Id = 5,
                            Wisdom = "Сложнее всего начать действовать, все остальное зависит только от упорства."
                        },
                        new
                        {
                            Id = 6,
                            Wisdom = "Надо любить жизнь больше, чем смысл жизни."
                        },
                        new
                        {
                            Id = 7,
                            Wisdom = "Жизнь - это то, что с тобой происходит, пока ты строишь планы."
                        },
                        new
                        {
                            Id = 8,
                            Wisdom = "Логика может привести Вас от пункта А к пункту Б, а воображение — куда угодно."
                        },
                        new
                        {
                            Id = 9,
                            Wisdom = "Через 20 лет вы будете больше разочарованы теми вещами, которые вы не делали, чем теми, которые вы сделали. Так отчальте от тихой пристани. Почувствуйте попутный ветер в вашем парусе. Двигайтесь вперед, действуйте, открывайте!"
                        },
                        new
                        {
                            Id = 10,
                            Wisdom = "Начинать всегда стоит с того, что сеет сомнения."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
