// <auto-generated />
using DrugBot.DataBase.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrugBot.DataBase.Migrations.Emoji
{
    [DbContext(typeof(EmojiDbContext))]
    [Migration("20240721074737_AddDataForTests")]
    partial class AddDataForTests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("DrugBot.DataBase.Data.EmojiData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Emojis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Emoji = "&#128512;"
                        },
                        new
                        {
                            Id = 2,
                            Emoji = "&#128515;"
                        },
                        new
                        {
                            Id = 3,
                            Emoji = "&#128516;"
                        },
                        new
                        {
                            Id = 4,
                            Emoji = "&#128513;"
                        },
                        new
                        {
                            Id = 5,
                            Emoji = "&#128518;"
                        },
                        new
                        {
                            Id = 6,
                            Emoji = "&#128517;"
                        },
                        new
                        {
                            Id = 7,
                            Emoji = "&#129315;"
                        },
                        new
                        {
                            Id = 8,
                            Emoji = "&#128514;"
                        },
                        new
                        {
                            Id = 9,
                            Emoji = "&#128578;"
                        },
                        new
                        {
                            Id = 10,
                            Emoji = "&#128579;"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
