name: Build and push docker image

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./src/
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/drugbot:latest

      - name: Notify Server via Netcat
        run: |
          # Здесь мы используем значения из секретов, чтобы передать их скрипту или команде.
          # Замените "YOUR_SERVER_IP" и "YOUR_SERVER_PORT" на названия секретов, которые вы создадите в настройках вашего репозитория.
          # Например, если вы назвали секрет с IP "SERVER_IP", используйте ${{ secrets.SERVER_IP }}.
          SERVER_IP="${{ secrets.YOUR_SERVER_IP }}"
          SERVER_PORT="${{ secrets.YOUR_SERVER_PORT }}"
          
          # Здесь предполагается, что ваш сервер ожидает сообщение в формате "build_complete",
          # иначе замените на то, что требуется вашему серверу.
          MESSAGE="build_complete"

          UPDATE_SERVER=${{ secrets.UPDATE_SERVER }}
  
          if [ "$UPDATE_SERVER" = "true" ]; then
            # Отправляем сообщение на сервер с помощью утилиты netcat (nc).
            # Предварительно убедитесь, что у вас установлен netcat на сервере.
            echo "$MESSAGE" | nc "$SERVER_IP" "$SERVER_PORT"
          fi